name:                HaskellTutorial
version:             0.1.0.0
github:              "nunulk/100DaysOfCode/HaskellTutorial"
license:             MIT
author:              "nunulk"
maintainer:          "nunulk@usingstd.com"
copyright:           "2018 nunulk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nunulk/100DaysOfCode/HaskellTutorial#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring

library:
  source-dirs: src

executables:
  HaskellTutorial-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellTutorial

tests:
  HaskellTutorial-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellTutorial
